; Local PHP 8.4 settings for Softloom (CodeIgniter 3 + dompdf)

allow_url_fopen = On
allow_url_include = On
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 300
max_input_time = 90
max_input_vars = 3000
memory_limit = 1512M
post_max_size = 64M
session.gc_maxlifetime = 1440
;session.save_path = "/tmp"
upload_max_filesize = 64M
zlib.output_compression = Off
sys_temp_dir = "/tmp"
upload_tmp_dir = "/tmp"
